{% set name = "napari-segment-anything" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-segment-anything-{{ version }}.tar.gz
  sha256: b45a479942b0e6aaf6f8a03b7f224aa185eec3e50bbb7d4ea9c4b14a31c1ef3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - pytorch
    - qtpy
    - segment-anything
    - torchvision

test:
  imports:
    - napari_segment_anything
  commands:
    - pip list
    # - pip check  # Fails due to segment-anything
  requires:
    - pip

about:
  home: https://github.com/jookuma/napari-segment-anything
  summary: Napari plugin of Segment Anything Model (SAM)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
